# Generated by Django 4.1.7 on 2023-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['created'], 'verbose_name_plural': 'Задания'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('content', models.TextField(verbose_name='Описание задачи')),
                ('task', models.ManyToManyField(blank=True, to='main.tasks', verbose_name='Категория')),
            ],
        ),
    ]
