# Generated by Django 4.1.7 on 2023-03-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Заголовок'),
        ),
    ]
