# Generated by Django 4.1.7 on 2023-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tasks_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='account',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено?'),
        ),
    ]
